import turtle
print(turtle.getshapes())
turtle.shape('turtle')
turtle.fd(200)
turtle.shape('circle')
turtle.fd(200)
turtle.shape('square')
turtle.hideturtle()
turtle.rt(90)
turtle.bk(100)
turtle.showturtle()
